""" This piece of code is going to be partially generated by AI (copilot) """

# def generate_random_dataset_for_classification():
#     """This function generates 3 columns, two with scalar values and a third with a categorical response, completely at random"""

import random
import pandas as pd
import numpy as np

def generate_data_at_random():
    """Generate data"""
    data = []
    for i in range(100):
        """Add data to a list"""
        data.append([random.random(), random.random(), random.choice(["A", "B", "C"])])
    
    """Convert list to numpy array"""
    data = np.array(data)

    """Convert list of lists to pandas dataframe"""
    data = pd.DataFrame(data, columns=['x1', 'x2', 'y'])
    return data


if __name__ == "__main__":
    mydata = generate_data_at_random()
    print(mydata)
    print(type(mydata))